### PR TITLE
Updated content for roles

### PR DESCRIPTION
**Pull request by phae**
Here is the /roles page with the updated content from https://docs.google.com/document/d/11jtdwNESFOJ2CT0urD8Y0o2P7VaYA2zUG1UREkI9L8E/edit#

@KimberlyglennTSM and Jen need to 👍 for it to go live.

### CODE REVIEW

**Comment by JenTress** [comment]
Hiya! Can I get an update on this @phae and / or @aaronhans? @KimberlyglennTSM and I are 👍on the content in the doc.

**Comment by aaronhans** [comment]
This was live and I was asked to take it down. Are we good to post now @kimberly @jp

**Comment by JenTress** [comment]
Hey @aaronhans the content that was live before wasn't up to date (thus the need to take it down). The content in the word doc above IS up to date and should go live. I'm syncing with Kimberly at 8 PST this morning so will ask her to come here and approve.

**Comment by aaronhans** [comment]
Thanks @KimberlyglennTSM the /roles page has been released with the latest content here

**Pull request merged**
