### PR TITLE
Stubbed out jobs

### PR DESCRIPTION
**Pull request by phae**
The URL is correct for that job, but not live.

This is the sort of very simple MVP layout I thought would work well for this. @KimberlyglennTSM should probably put her eyes on it and improve the language in that intro section!

### CODE REVIEW

**Comment by phae** [comment]
@aaronhans at some point can you 👍 or not to merge this into your /jobs branch?  Also, you're going to hate this, but we need to change /jobs to /roles :)

**Comment by aaronhans** [comment]
Cool, Kimberly mentioned that word change. 

@KimberlyglennTSM are we good to release it after changing url from /jobs/ to /roles/?

**Comment by aaronhans** [comment]
PR to merge to master which will deploy the update is here https://github.com/cagov/news/pull/13

**Comment by KimberlyglennTSM** [comment]
Hi Aaron, Yes I am!  Thank you for checking

**Comment by abquirarte** [comment]
Can someone send me the link when done?
Kimberly I want to brief you on something related to this.

Thanks all!
Angelica Quirarte, "Angie"
Assistant Secretary- Government Operations Agency
c: 916-526-5510
Digital Crisis Standard- covid19.ca.gov
<https://github.com/cagov/covid19/wiki/Crisis-Standard>

Follow us:
Web <https://alpha.ca.gov/> | Blog <https://medium.com/cadotgov> | Twitter
<https://twitter.com/cadotgov>

**Comment by aaronhans** [comment]
Thanks for creating this @phae we are live here @abquirarte  https://news.alpha.ca.gov/roles/ not linking to it anywhere yet

**Comment by abquirarte** [comment]
looks awesome!
Angelica Quirarte, "Angie"
Assistant Secretary- Government Operations Agency
c: 916-526-5510
Digital Crisis Standard- covid19.ca.gov
<https://github.com/cagov/covid19/wiki/Crisis-Standard>

Follow us:
Web <https://alpha.ca.gov/> | Blog <https://medium.com/cadotgov> | Twitter
<https://twitter.com/cadotgov>

**Comment by KimberlyglennTSM** [comment]
Angie, do you want me to schedule time on your calendar for the briefing?

Thank you,
Kimberly
*Kimberly Glenn*
Team Success & Delivery Manager
c. 916-270-3515
Kimberly.Glenn@Alpha.ca.gov
Alpha.CA.gov <http://alpha.ca.gov/>
Follow us: Web | Blog | Twitter

**Pull request merged**
